### ISSUE TITLE
Dapper.FastCrud.ModelGenerator class access modifier

### ISSUE THREAD

**Issue by kipusoep** [MoonStorm/FastCrud#104]
It would be great to be able to configure the access modifier of the generated models, so they can be internal instead of public for example.

**Comment by MoonStorm** [comment]
That can be easily achieved by adding a config property in the config .tt file and using it inside the model generator .tt file. A pull request for this would be really appreciated.

**Comment by a-priestley** [comment]
Just wondering if we can make the same change for generated properties to add `= default!;` ? (handling Warning CS8618)

**Comment by MoonStorm** [comment]
Added customizations for both the class and the property modifiers.
Also added a warning pragma for CS8618.
