### ISSUE TITLE
FastCrud seems to ignore TableAttribute on Entities on v3

### ISSUE THREAD

**Issue by bpress** [MoonStorm/FastCrud#156]
Just recompiled my project with FastCrud 3.0.45.
I have a bunch of entities exposing the TableAttribute in order to map entities to table names which are different from the class name.
It looks like FastCrud is ignoring the TableAttribute and is trying to build sql using the entity class names anyway.

When recompiling with 2.6.7 it works.

**Comment by MoonStorm** [comment]
All our tests are passing, including both code first and fluent registrations. We have changed the name of all our entities in our tests as well, just to make sure. [Here](https://github.com/MoonStorm/FastCrud/blob/master/Dapper.FastCrud.Tests/Models/CodeFirst/BadgeDbEntity.cs) is an example. Can you provide more information please? What kind of operations are failing for you? Maybe we missed something.

**Comment by bpress** [comment]
My bad!
I was relying on EntityMapping.TableName property to perform an upsert operation inside an extension method of mine.
I saw you refactored EntityMapping, which now does not expose a TableName property anymore.... 
Sorry for opening the issue without a more in-depth preliminary checking on my side.
