### ISSUE TITLE
it's more complex

### ISSUE THREAD

**Issue by wuzhenda** [MoonStorm/FastCrud#178]
can't write the code without document.

`    var queryParams = new 
    {
        FirstName = "John",
        Street = "Creek Street"
    };

    var persons = dbConnection.Find<Person>(statement => statement
        .WithAlias("person")
        .Include<Address>(join => join.InnerJoin()
                                      .WithAlias("address"))
        .Where($@"
           {nameof(Person.FirstName):of person} = {nameof(queryParams.FirstName):P} 
           AND {nameof(Address.Street):of address} = {nameof(queryParams.Street):P}")  
        .OrderBy($"{nameof(Person.LastName):of person} DESC")  
        .Skip(10)  
        .Top(20)  
        .WithParameters(queryParams);`

**Comment by wuzhenda** [comment]
and changed "Dapper.FastCrud.ModelGenerator" class name?

**Comment by MoonStorm** [comment]
You're gonna have to be more specific. What "document" are you missing?

**Comment by wuzhenda** [comment]
have to go back here for wiki document time by time.
for the code like that  not easy to remember.

**Comment by MoonStorm** [comment]
Ah I see. Thanks for bringing this to our attention.
