### ISSUE TITLE
Referencing unpublished Dapper in NuGet

### ISSUE THREAD

**Issue by the-black-wolf** [MoonStorm/FastCrud#200]
Last two released versions of Dapper.FastCrud require Dapper >= 2.1.37

Last released Dapper is 2.1.35

EDIT: Actually they have delisted all versions after 2.1.35 themselves. wth is happening?

https://www.nuget.org/packages/Dapper/2.1.44

![image](https://github.com/MoonStorm/FastCrud/assets/15175507/b195067a-5e17-471a-9671-12b15e24c5d8)

**Comment by MoonStorm** [comment]
``DateOnly`` and ``TimeOnly`` are [exactly the reason why they pulled the release](https://github.com/DapperLib/Dapper/issues/2075#issuecomment-2124585749). It doesn't really matter tbh, we've sorted this on our side [in the good old type handling fashion](https://github.com/MoonStorm/FastCrud/wiki/Property-value-type-mappings#dateonly-and-timeonly). It is a manual step indeed, but it's better than nothing in this case.

Thanks for bringing this to my attention. I already pushed a new version with a listed reference of ``Dapper``.
