### ISSUE TITLE
Log generated sql query

### ISSUE THREAD

**Issue by mkeymolen** [MoonStorm/FastCrud#55]
It's not really an issue, it's just a possible enhancement. When i find some time, i'll see if i can do it on a fork and create a pull request for it. What i want to do is the following:
In a certain situation, i would like to log the generated sql query to the console.
When i have difficulties with dataqueries, i can setup sql profiler on MSSQL to see what sql query Fastcrud has generated, but it is not always possible to setup sql profiler(example sqlite). It would be great if we could have a way to see which sql query is send to Dapper to be executed.

**Comment by moxplod** [comment]
I find this free tool to be really helpful for that purpose - not sure if that would work with sqllite. But works AMAZING with sql server. It gives full query with all parameters http://stackify.com/prefix.

**Comment by MoonStorm** [comment]
Don't need to do anything. Just watch the SQL statements in VS2015 while debugging normally.

**Comment by mkeymolen** [comment]
ok, i'll try it out this weekend. btw, @MoonStorm you created a fantastic library!

**Comment by vitidev** [comment]
Dapper shows sql in output window, but fastcrud not. and it saddens

**Comment by jafin** [comment]
Try MiniProfiler?  http://stackoverflow.com/questions/14318571/how-to-read-an-sql-query-generated-by-dapper

**Comment by mkeymolen** [comment]
As soon i have some freetime the following weeks, i'll try to implement something generic to log the sql query and do a pull request.

**Comment by kipusoep** [comment]
@mkeymolen and did you? ;-)

**Comment by mkeymolen** [comment]
@kipusoep Not yet. Working with entityframework core nowadays. I'll see later in 2018. Sorry

**Comment by kipusoep** [comment]
I don't see any SQL queries in Intellitrace with Dapper FastCRUD. With Entity Framework I do see them.

**Comment by MoonStorm** [comment]
It has finally stopped working for me as well. I'm assuming it's a problem between .NET Core and the Intellitrace implementation in Visual Studio. Either way, the best way to see the actual SQL, including the parameters, is to use the SQL Profiler whilst your code is running.
