### ISSUE TITLE
OrmConfiguration.GetDefaultEntityMapping(Type)

### ISSUE THREAD

**Issue by vitidev** [MoonStorm/FastCrud#58]
It is necessary to have OrmConfiguration.GetDefaultEntityMapping(Type).

**Comment by generik0** [comment]
Hi, i am not moonstorm, nor accosiated with the project. but maybe i can help. I have used it somewhat.

What are you using "OrmConfiguration.GetDefaultEntityMapping(Type)." for?

What is it you are asking "It is necessary to have". You don't like that it is static?

**Comment by vitidev** [comment]
@generik0 I need resolve tablename for entity in not generic method, where I have no <T>, only entity.GetType(), and I am forced to use reflection to call OrmConfiguration.GetDefaultEntityMapping<T>()

**Comment by generik0** [comment]
Ok. But are you not using a repository pattern for your sql work? Then you will always have the entity as a generic...

Otherwise, how about getting your table names for a dictionary with the key as the type. I haven't checked but can't you use the dictionary value in the entity table name also?

**Comment by generik0** [comment]
You might be able to use fasterfelct if you absolutely have to get the table name...

When you have the table name you can always store in a concurrent dictionary so you only use reflections once...?

**Comment by vitidev** [comment]
@generik0 
> But are you not using a repository pattern for your sql work?

No. Repository pattern has many disadvantages. I have used it for many years.
I use "QueryObject/CQS pattern" from [there](https://cuttingedge.it/blogs/steven/pivot/entry.php?id=91), where  is **very widely used DI container for resolving** concrete QueryObject/Command class

We have:

     interface IEntity{
         long Id {get;set;}
     }
     class Asset: IEntity{....}
     class Post: IEntity{....}

Next, I want to write a general query for bulk delete entity list by id
I[ do not know how do this in FastCrud](https://github.com/MoonStorm/Dapper.FastCRUD/issues/60), so I use dapper level

    class BulkDeleteHandler<T>: ICommandHandler<BulkDeleteCommand<T>>
          where T: IEntity
    {
        public void Handle(BulkDeleteCommand<T> command)
        {
            using (var db = _connector.Connect())
            {
                var table = OrmConfiguration.GetDefaultEntityMapping<T>().TableName
                db.Execute($"DELETE FROM {table} WHERE Id IN @Ids",
                    new {Ids = command.Entities.Select(e => e.Id).ToArray()});
            }
        }
    }

but for unknown reason (DI container limitations) type resolving not work with `where T: IEntity`, so result

    class BulkDeleteHandler: ICommandHandler<BulkDeleteCommand>
    {
        public void Handle(BulkDeleteCommandcommand)
        {
            using (var db = _connector.Connect())
            {
                //oops. we knows that type is IEntity, but we have no <T>
                var table = EntityExt.GetTableNameForEntity(command.Entities.First()); //reflection hack
                db.Execute($"DELETE FROM {table} WHERE Id IN @Ids",
                    new {Ids = command.Entities.Select(e => e.Id).ToArray()});
            }
        }
    }

It is work, but the use of reflection is bad

**Comment by generik0** [comment]
Interresting... I have only used CQS pattern for communications, never database (even though database is a form of communication :- )

Well it looks like your root cause is issues with the IoC. What IoC are you using?
I understand the issues you have felt with repo pattern hence i have started this:
https://github.com/generik0/Smooth.IoC.Dapper.Repository.UnitOfWork
(check it out, let me know what you think...)

You see, personally i would probably combine the CQS with a repository so you constructor inject the entity repo into the command handler. But people are different and one mans OCD is another mans mess :-)

Is it simple injector? Have you tried with where T : class, IEntity?

**Comment by generik0** [comment]
Was doing som work. FOund that Sql.Table<Entity() will actually give you the table name. 
I know it wont help you as you don't have the generic.... But thought it might be interesting :-)

**Comment by vitidev** [comment]
>let me know what you think

There are no benefits from UnitOfWork pattern in my project.

I made explicit registration concrete generic type with `where T : class, IEntity` and it worked

However, methods `OrmConfiguration.GetDefaultEntityMapping<T>`, `Sql.Table<T>`, etc have no overloads with `(Type type)`
The tasks are different and not always available generics

**Comment by generik0** [comment]
I looked into the source code. Most of the places the generic is being used with a typeof. Hence there could be an overload with (Type type)
But I did deep down find the generic being used in a different way.

All I can recommend is trying to add a type overload and see how far you get?

Sorry I couldn't be more help. 

If your generic with T is passing now with the IoC doesn't the solution work for you as is?

Btw I do see your point with bulkdelete entities:-)

**Comment by vitidev** [comment]
@generik0 
My problem was solved by `where T : class, IEntity`

but I still think that generic methods `OrmConfiguration.GetDefaultEntityMapping<T>`, `Sql.Table<T>` must have overloads with `(Type type)`. 

When writing extensions is quite typical situation where we have instance that was casted to base type and we need to get mapping for real type. For example, we need build set of complex queries to save complex entity to several tables.

**Comment by MoonStorm** [comment]
I did take another look at this but unfortunately it's not possible to have overloads with ``Type``. The generic type is used to create the type's specific sql builder and statements, which are all generic.
