### ISSUE TITLE
How to use Dapper.FastCrud.ModelGenerator ?

### ISSUE THREAD

**Issue by ysfb2000** [MoonStorm/FastCrud#77]
I have installed Dapper.FastCrud.ModelGenerator package into my class library via Nuget. But there no a folder named 'models' or *.tt files in the class library.

I want to automatic generate models from database, what shall I do?

My development environment is VS2017， asp.net core project, the class library is .NET Standard.

**Comment by iulianEduard** [comment]
I have the same issue, the Models folder did not generate for .NET Core project, however when testing on regular .NET framework the folder was created.

**Comment by naveenkumarmark** [comment]
I have the same issue. I have installed the plugin through nuget but no folder or files is created

**Comment by naveenkumarmark** [comment]
Hi I have found the solution to the problem of generating entity.
1. Add Dapper.FastCrud.ModelGenerator to the project
2. Create a folder in the project to keep our entity models
3. Add these 2 files within the created folder https://github.com/MoonStorm/Dapper.FastCRUD/tree/master/Dapper.FastCrud.ModelGenerator/Content/Models
4. Change the Namespace = ""; in SampleModelGeneratorConfig.tt to your project name space 
5. Create a config file and  
<?xml version="1.0" encoding="utf-8"?>
    <configuration>
        <connectionStrings>
          <add name="EntityGeneration"  
               providerName="System.Data.SqlClient"   
               connectionString="Data Source=LocalDb)\v11.0;AttachDbFilename=|DataDirectory|\TestDatabase.mdf;Initial Catalog=TestDatabase;Integrated Security=True" />
        </connectionStrings>
    </configuration
6. Now right click on the SampleModelGeneratorConfig.tt and you will see the option 
 * Debug T4 Template * and click on it

you can generate entity following this link (https://github.com/MoonStorm/Dapper.FastCRUD)

**Comment by MoonStorm** [comment]
One of the Visual Studios broke the T4 templates. We've reworked them for VS2019 and up and they should be working fine now.
Here are a few tips: [https://github.com/MoonStorm/FastCrud/wiki/Entity-registration#database-first-approach-via-a-t4-template-from-a-database-schema-limited-to-sql-server](https://github.com/MoonStorm/FastCrud/wiki/Entity-registration#database-first-approach-via-a-t4-template-from-a-database-schema-limited-to-sql-server)
